[template]

# Required. The name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/confd/templates` for these files by default
src         = "server.properties.tmpl"

# Required. The location to place the rendered configuration file.
# TODO: this should use the KAFKA_HOME environment variable.
dest        = "/opt/kafka/config/server.properties"

# Required. The etcd keys or directory to watch.  This is where the information to fill in
# the template will come from.
keys        = [ "/services/zookeeper" ]

# File ownership and mode information
owner       = "root"
mode        = "0644"

# These are the commands that will be used to check whether the rendered config is
# valid and to reload the actual service once the new config is in place
# check_cmd  = 
reload_cmd  = "/opt/kafka/bin/kafka-server-stop.sh && /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties"